[buildPlans.ioseyka]
family = "Ioseyka"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.ioseyka.variants]
  inherits = "ss15"

    [buildPlans.ioseyka.variants.design]
    long-s = "bent-hook-serifless"
    eszet = "longs-s-lig"
    zero = "tall-reverse-slashed"
    three = "flat-top"

  [buildPlans.ioseyka.ligations]
  inherits = "dlig"