col-foreground: &col-foreground 66666CFF
col-active: &col-active DCD7BAff
col-background: &col-background 282828FF

bar:
  height: 30
  location: top
  background: 282828ff
  font: CaskaydiaCode NF:pixelsize=14

  
  left:
    - script:
        path: ~/.config/yambar/scripts/hyprland.sh
        args: [] 
        content:
          map:
            conditions:
              workspace == 1:
                - string: {text: "1",foreground: *col-active, on-click: "hyprctl dispatch workspace 1", margin: 6}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 2:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-active, on-click: "hyprctl dispatch workspace 2", margin: 6}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 3:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-active, on-click: "hyprctl dispatch workspace 3", margin: 6}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 4:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-active, on-click: "hyprctl dispatch workspace 4", margin: 6}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 5:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-active, on-click: "hyprctl dispatch workspace 5", margin: 6}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 6:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-active, on-click: "hyprctl dispatch workspace 6", margin: 6}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 7:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-active, on-click: "hyprctl dispatch workspace 7", margin: 6}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 8:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-active, on-click: "hyprctl dispatch workspace 8", margin: 6}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 9:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-active, on-click: "hyprctl dispatch workspace 9", margin: 6}
                - string: {text: "10",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 10", margin: 3}
              workspace == 10:
                - string: {text: "1",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 1", margin: 3}
                - string: {text: "2",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 2", margin: 3}
                - string: {text: "3",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 3", margin: 3}
                - string: {text: "4",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 4", margin: 3}
                - string: {text: "5",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 5", margin: 3}
                - string: {text: "6",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 6", margin: 3}
                - string: {text: "7",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 7", margin: 3}
                - string: {text: "8",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 8", margin: 3}
                - string: {text: "9",foreground: *col-foreground, on-click: "hyprctl dispatch workspace 9", margin: 3}
                - string: {text: "10",foreground: *col-active, on-click: "hyprctl dispatch workspace 10", margin: 6}


  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{title}"}

  right:
    - clock:
        content:
          string:
            margin: 10
            text: "{time}"
            on-click: "notify-send '{date}, {time}'"
