#! /bin/sh

# Sxhkd
pgrep -x sxhkd > /dev/null # || sxhkd -c ~/.config/bspwm/sxhkdrc &
sxhkd &

# Bar
exec /home/tilman/.config/polybar/launcher_bspwm.sh &

# Picom
picom &

# Dunst
pkill dunst
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a pulsemixer state=floating
bspc rule -a mpv state=fullscreen

# Wallpaper
feh --bg-scale ~/.config/walls/color-wave-gruv.png

# Caffeine
caffeine &
