[colors]
background = '#090a14'
foreground = '#ebede9'
cursor_fg = '#090a14'
cursor_bg = '#090a14'
cursor_border = '#ebede9'

ansi = [
  '#10141f',
  '#a53030',
  '#75a743',
  '#be772b',
  '#3c5e8b',
  '#7a367b',
  '#73bed3',
  '#a8b5b2',
]

brights = [
  '#151d28',
  '#cf573c',
  '#a8ca58',
  '#de9e41',
  '#4f8fba',
  '#a23e8c',
  '#a4dddb',
  '#c7cfcc',
]

[metadata]
name = 'Apollo'
origin_url = 'https://lospec.com/palette-list/apollo'
