#! /bin/sh

CHOSEN=$(printf "Power Off\nRestart\nLock\nLogout" | rofi -p "Powermenu" -dmenu)

case $CHOSEN in
  "Power Off") sudo shutdown now ;;
  "Restart") sudo reboot now ;;
  "Lock") i3lock -i ~/pix/walls/leine.png -Lk --time-color=fbf1c7 --date-color=fbf1c7 --greeter-color=fbf1c7 ring-color=98971a --time-str="%H:%M" --date-str="%a, %d.%m.%y" ;;
  "Logout") loginctl terminate-user $USER ;;
  *) exit 1 ;;
esac
