#! /bin/sh

OUTPUT=$HOME/pix/screenshots/%Y_%m_%d_%T-screenshot.png

case $1 in
  "select") scrot "$OUTPUT" --select --line mode=edge || exit ;;
  "window") scrot "$OUTPUT" --focused --border || exit ;;
  *) exit 1 ;;
esac
