theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
color-modes = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
rainbow-option = "dim"
character = "│"

[editor.statusline]
left = ["mode", "spacer", "file-name", "position", "position-percentage", "spacer", "spinner"]
center = []
right = ["diagnostics", "spacer", "file-type"]
separator = "|"

[editor.statusline.mode]
insert = "<I>"
normal = "<N>"
select = "<V>"

[editor.lsp]
display-inlay-hints = true
snippets = true
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
q = ":q"
"/" = "toggle_comments"

[keys.normal."space".f]
f = "file_picker"
s = ":w"
w = "global_search"

