theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
rainbow-option = "dim"
character = "│"

[editor.statusline]
left = ["mode", "file-modification-indicator", "file-name", "position", "position-percentage", "spacer", "spinner"]
center = []
right = ["diagnostics", "spacer", "file-type"]
separator = "|"

[editor.statusline.mode]
insert = "<I>"
normal = "<N>"
select = "<V>"

[editor.lsp]
display-inlay-hints = true
snippets = true


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

